# week-1 Tokenizer

In [22]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer

In [23]:
sentence = [
    'আমার একটি গরু আছে',
    'আমার একটি মহিষ আছে',
    'তোমার একটি গরু আছে!',
    'তুমি কি মনে কর আমার গরু তরতাজা'
]

In [24]:
tokenizer = Tokenizer(num_words=100)
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)
print(word_index)
print(sequences)

{'আমার': 1, 'একটি': 2, 'গরু': 3, 'আছে': 4, 'মহিষ': 5, 'তোমার': 6, 'তুমি': 7, 'কি': 8, 'মনে': 9, 'কর': 10, 'তরতাজা': 11}
[[1, 2, 3, 4], [1, 2, 5, 4], [6, 2, 3, 4], [7, 8, 9, 10, 1, 3, 11]]


In [25]:
test_data = [
    'আমার আসলেই একটু গরু আছে',
    'আমার গরু ঘাস খায়'
]
test_seq = tokenizer.texts_to_sequences(test_data)
print(test_seq)

[[1, 3, 4], [1, 3]]


In [26]:
tokenizer = Tokenizer(num_words=100,oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)
print(word_index)
print(sequences)

{'<OOV>': 1, 'আমার': 2, 'একটি': 3, 'গরু': 4, 'আছে': 5, 'মহিষ': 6, 'তোমার': 7, 'তুমি': 8, 'কি': 9, 'মনে': 10, 'কর': 11, 'তরতাজা': 12}
[[2, 3, 4, 5], [2, 3, 6, 5], [7, 3, 4, 5], [8, 9, 10, 11, 2, 4, 12]]


In [27]:
test_data = [
    'আমার আসলেই একটু গরু আছে',
    'আমার গরু ঘাস খায়'
]
test_seq = tokenizer.texts_to_sequences(test_data)
print(test_seq)

[[2, 1, 1, 4, 5], [2, 4, 1, 1]]


# Padding

In [28]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [29]:
sentence = [
    'আমার একটি গরু আছে',
    'আমার একটি মহিষ আছে',
    'তোমার একটি গরু আছে!',
    'তুমি কি মনে কর আমার গরু তরতাজা'
]

In [30]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)

padded = pad_sequences(sequences)
print(word_index)
print(sequences)
print(padded)

{'<OOV>': 1, 'আমার': 2, 'একটি': 3, 'গরু': 4, 'আছে': 5, 'মহিষ': 6, 'তোমার': 7, 'তুমি': 8, 'কি': 9, 'মনে': 10, 'কর': 11, 'তরতাজা': 12}
[[2, 3, 4, 5], [2, 3, 6, 5], [7, 3, 4, 5], [8, 9, 10, 11, 2, 4, 12]]
[[ 0  0  0  2  3  4  5]
 [ 0  0  0  2  3  6  5]
 [ 0  0  0  7  3  4  5]
 [ 8  9 10 11  2  4 12]]


# padding post

In [31]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)

padded = pad_sequences(sequences, padding='post')
print(word_index)
print(sequences)
print(padded)

{'<OOV>': 1, 'আমার': 2, 'একটি': 3, 'গরু': 4, 'আছে': 5, 'মহিষ': 6, 'তোমার': 7, 'তুমি': 8, 'কি': 9, 'মনে': 10, 'কর': 11, 'তরতাজা': 12}
[[2, 3, 4, 5], [2, 3, 6, 5], [7, 3, 4, 5], [8, 9, 10, 11, 2, 4, 12]]
[[ 2  3  4  5  0  0  0]
 [ 2  3  6  5  0  0  0]
 [ 7  3  4  5  0  0  0]
 [ 8  9 10 11  2  4 12]]


# Padding maxlen

In [32]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)

padded = pad_sequences(sequences, padding='post',maxlen=5)
print(word_index)
print(sequences)
print(padded)

{'<OOV>': 1, 'আমার': 2, 'একটি': 3, 'গরু': 4, 'আছে': 5, 'মহিষ': 6, 'তোমার': 7, 'তুমি': 8, 'কি': 9, 'মনে': 10, 'কর': 11, 'তরতাজা': 12}
[[2, 3, 4, 5], [2, 3, 6, 5], [7, 3, 4, 5], [8, 9, 10, 11, 2, 4, 12]]
[[ 2  3  4  5  0]
 [ 2  3  6  5  0]
 [ 7  3  4  5  0]
 [10 11  2  4 12]]


In [33]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)

padded = pad_sequences(sequences, maxlen=5)
print(word_index)
print(sequences)
print(padded)

{'<OOV>': 1, 'আমার': 2, 'একটি': 3, 'গরু': 4, 'আছে': 5, 'মহিষ': 6, 'তোমার': 7, 'তুমি': 8, 'কি': 9, 'মনে': 10, 'কর': 11, 'তরতাজা': 12}
[[2, 3, 4, 5], [2, 3, 6, 5], [7, 3, 4, 5], [8, 9, 10, 11, 2, 4, 12]]
[[ 0  2  3  4  5]
 [ 0  2  3  6  5]
 [ 0  7  3  4  5]
 [10 11  2  4 12]]


# Padding Truncating 

In [34]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)

padded = pad_sequences(sequences, padding='post',maxlen=5,truncating='post')
print(word_index)
print(sequences)
print(padded)

{'<OOV>': 1, 'আমার': 2, 'একটি': 3, 'গরু': 4, 'আছে': 5, 'মহিষ': 6, 'তোমার': 7, 'তুমি': 8, 'কি': 9, 'মনে': 10, 'কর': 11, 'তরতাজা': 12}
[[2, 3, 4, 5], [2, 3, 6, 5], [7, 3, 4, 5], [8, 9, 10, 11, 2, 4, 12]]
[[ 2  3  4  5  0]
 [ 2  3  6  5  0]
 [ 7  3  4  5  0]
 [ 8  9 10 11  2]]


In [35]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(sentence)
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(sentence)

padded = pad_sequences(sequences, maxlen=5,padding='pre', truncating='pre')
print(word_index)
print(sequences)
print(padded)

{'<OOV>': 1, 'আমার': 2, 'একটি': 3, 'গরু': 4, 'আছে': 5, 'মহিষ': 6, 'তোমার': 7, 'তুমি': 8, 'কি': 9, 'মনে': 10, 'কর': 11, 'তরতাজা': 12}
[[2, 3, 4, 5], [2, 3, 6, 5], [7, 3, 4, 5], [8, 9, 10, 11, 2, 4, 12]]
[[ 0  2  3  4  5]
 [ 0  2  3  6  5]
 [ 0  7  3  4  5]
 [10 11  2  4 12]]


# Pandas read_json file

In [36]:
# import pandas as pd 
# datastore = pd.read_json('/Users/msjahid/Desktop/NLP/sarcasm.json')
# datastore.head()

In [37]:
import json
with open('/Users/msjahid/Desktop/NLP/sarcasm.json', 'r') as f:
    datastore = json.load(f)

In [38]:
sentences = []
lable = []
urls = []
for item in datastore:
    sentences.append(item['headline'])
    lable.append(item['is_sarcastic'])
    urls.append(item['article_link'])

# Padding Shape

In [44]:
!wget --no-check-certificate \
    https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json \
    -O /tmp/sarcasm.json

--2020-03-12 10:48:58--  https://storage.googleapis.com/laurencemoroney-blog.appspot.com/sarcasm.json
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.24.128
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.24.128|:443... connected.
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 5643545 (5.4M) [application/json]
Saving to: ‘/tmp/sarcasm.json’

/tmp/sarcasm.json   100%[===================>]   5.38M   400KB/s    in 19s     

2020-03-12 10:49:18 (294 KB/s) - ‘/tmp/sarcasm.json’ saved [5643545/5643545]

[  308 15115   679  3337  2298    48   382  2576 15116     6  2577  8434
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0]
(26709, 40)


In [46]:
import json

with open("/tmp/sarcasm.json", 'r') as f:
    datastore = json.load(f)


sentences = [] 
labels = []
urls = []
for item in datastore:
    sentences.append(item['headline'])
    labels.append(item['is_sarcastic'])
    urls.append(item['article_link'])



from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer(oov_token="<OOV>")
tokenizer.fit_on_texts(sentences)

word_index = tokenizer.word_index
print(len(word_index))
print(word_index)
sequences = tokenizer.texts_to_sequences(sentences)
padded = pad_sequences(sequences, padding='post')
print(padded[0])
print(padded.shape)

29657
{'<OOV>': 1, 'to': 2, 'of': 3, 'the': 4, 'in': 5, 'for': 6, 'a': 7, 'on': 8, 'and': 9, 'with': 10, 'is': 11, 'new': 12, 'trump': 13, 'man': 14, 'from': 15, 'at': 16, 'about': 17, 'you': 18, 'this': 19, 'by': 20, 'after': 21, 'up': 22, 'out': 23, 'be': 24, 'how': 25, 'as': 26, 'it': 27, 'that': 28, 'not': 29, 'are': 30, 'your': 31, 'his': 32, 'what': 33, 'he': 34, 'all': 35, 'just': 36, 'who': 37, 'has': 38, 'will': 39, 'more': 40, 'one': 41, 'into': 42, 'report': 43, 'year': 44, 'why': 45, 'have': 46, 'area': 47, 'over': 48, 'donald': 49, 'u': 50, 'day': 51, 'says': 52, 's': 53, 'can': 54, 'first': 55, 'woman': 56, 'time': 57, 'like': 58, 'her': 59, "trump's": 60, 'old': 61, 'no': 62, 'get': 63, 'off': 64, 'an': 65, 'life': 66, 'people': 67, 'obama': 68, 'now': 69, 'house': 70, 'still': 71, "'": 72, 'women': 73, 'make': 74, 'was': 75, 'than': 76, 'white': 77, 'back': 78, 'my': 79, 'i': 80, 'clinton': 81, 'down': 82, 'if': 83, '5': 84, 'when': 85, 'world': 86, 'could': 87, 'we': 8

[  308 15115   679  3337  2298    48   382  2576 15116     6  2577  8434
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0]
(26709, 40)


In [47]:
sentences[0]

"former versace store clerk sues over secret 'black code' for minority shoppers"

In [48]:
padded = pad_sequences(sequences)
print(padded[0])

[    0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0     0     0     0     0     0     0     0     0
     0     0     0     0   308 15115   679  3337  2298    48   382  2576
 15116     6  2577  8434]


In [49]:
import pandas as pd 
import numpy as np 

In [50]:
bangla = pd.read_csv('/Users/msjahid/Downloads/content_2019 2.csv')

In [51]:
bangla.head()

date                                              title  \
0  2019-01-01        মুক্তিযুদ্ধ-গবেষণার বর্ণনা তাজুল মোহাম্মদের   
1  2019-01-01                   নতুন বছরে তারকাদের পরিকল্পনা কী?   
2  2019-01-01    আফগানিস্তানে যুক্তরাষ্ট্রের পরবর্তী পদক্ষেপ কী?   
3  2019-01-01                    সন্তানদের জন্য স্যান্ড্রার চিঠি   
4  2019-01-01  সুনামগঞ্জে ২২. হবিগঞ্জে ১৬ প্রার্থীর জামানত বা...   

                           subtitle                                 author  \
0  টরন্টোয় পাঠশালার বিজয় দিবসের আসর                     উত্তর আমেরিকা অফিস   
1                               NaN              হাবিবুল্লাহ সিদ্দিক. ঢাকা   
2                         ভূরাজনীতি                      মাইকেল কুগেলম্যান   
3                               NaN                           বিনোদন ডেস্ক   
4                               NaN  নিজস্ব প্রতিবেদক. সুনামগঞ্জ ও হবিগঞ্জ   

  comment                                                ref        section  \
0     NaN  https://www.prothomalo.com/northamerica/articl...   northamerica   
1     NaN  https://www.prothomalo.com/entertainment/artic...  entertainment   
2     NaN  https://www.prothomalo.com/opinion/article/157...        opinion   
3     NaN  https://www.prothomalo.com/entertainment/artic...  entertainment   
4       ২  https://www.prothomalo.com/bangladesh/article/...     bangladesh   

   media  page                                               tags  \
0  print     1                                                NaN   
1  print     1                                           টেলিভিশন   
2  print     1                                        আন্তর্জাতিক   
3  print     1                                              হলিউড   
4  print     1  সুনামগঞ্জ|একাদশ সংসদ নির্বাচন|বিএনপি|আওয়ামী লী...   

                                             content  article_id  
0  দর্শন-শিল্প-সাহিত্য-বিজ্ঞান চর্চার প্ল্যাটফর্ম...     1572837  
1  শুরু হলো নতুন বছর। সবার মতো তারকাদেরও আছে বছরজ...     1572804  
2  এই মুহূর্তে জালমে খলিলজাদ সম্ভবত সুখী মানুষ নন...     1572798  
3  নেটফ্লিক্স অরিজিনালসের ‘বার্ড বক্স’ ছবিটি নিয়ে...     1572785  
4  নির্বাচনী আইন অনুযায়ী পর্যাপ্ত ভোট না পাওয়ায় স...     1572778

In [52]:
bangla.fillna('দেওয়া নাই', inplace=True)

In [53]:
bangla.head()

date                                              title  \
0  2019-01-01        মুক্তিযুদ্ধ-গবেষণার বর্ণনা তাজুল মোহাম্মদের   
1  2019-01-01                   নতুন বছরে তারকাদের পরিকল্পনা কী?   
2  2019-01-01    আফগানিস্তানে যুক্তরাষ্ট্রের পরবর্তী পদক্ষেপ কী?   
3  2019-01-01                    সন্তানদের জন্য স্যান্ড্রার চিঠি   
4  2019-01-01  সুনামগঞ্জে ২২. হবিগঞ্জে ১৬ প্রার্থীর জামানত বা...   

                           subtitle                                 author  \
0  টরন্টোয় পাঠশালার বিজয় দিবসের আসর                     উত্তর আমেরিকা অফিস   
1                         দেওয়া নাই              হাবিবুল্লাহ সিদ্দিক. ঢাকা   
2                         ভূরাজনীতি                      মাইকেল কুগেলম্যান   
3                         দেওয়া নাই                           বিনোদন ডেস্ক   
4                         দেওয়া নাই  নিজস্ব প্রতিবেদক. সুনামগঞ্জ ও হবিগঞ্জ   

     comment                                                ref  \
0  দেওয়া নাই  https://www.prothomalo.com/northamerica/articl...   
1  দেওয়া নাই  https://www.prothomalo.com/entertainment/artic...   
2  দেওয়া নাই  https://www.prothomalo.com/opinion/article/157...   
3  দেওয়া নাই  https://www.prothomalo.com/entertainment/artic...   
4          ২  https://www.prothomalo.com/bangladesh/article/...   

         section  media  page  \
0   northamerica  print     1   
1  entertainment  print     1   
2        opinion  print     1   
3  entertainment  print     1   
4     bangladesh  print     1   

                                                tags  \
0                                          দেওয়া নাই   
1                                           টেলিভিশন   
2                                        আন্তর্জাতিক   
3                                              হলিউড   
4  সুনামগঞ্জ|একাদশ সংসদ নির্বাচন|বিএনপি|আওয়ামী লী...   

                                             content  article_id  
0  দর্শন-শিল্প-সাহিত্য-বিজ্ঞান চর্চার প্ল্যাটফর্ম...     1572837  
1  শুরু হলো নতুন বছর। সবার মতো তারকাদেরও আছে বছরজ...     1572804  
2  এই মুহূর্তে জালমে খলিলজাদ সম্ভবত সুখী মানুষ নন...     1572798  
3  নেটফ্লিক্স অরিজিনালসের ‘বার্ড বক্স’ ছবিটি নিয়ে...     1572785  
4  নির্বাচনী আইন অনুযায়ী পর্যাপ্ত ভোট না পাওয়ায় স...     1572778

In [54]:
tokenizer.fit_on_texts(bangla['title'])

word_index = tokenizer.word_index
print(len(word_index))
print(word_index)
sequences = tokenizer.texts_to_sequences(bangla['title'])
padded = pad_sequences(sequences, padding='post')
print(padded[0])
print(padded.shape)

60189
{'<OOV>': 1, 'to': 2, 'of': 3, 'the': 4, 'in': 5, 'for': 6, 'a': 7, 'on': 8, 'and': 9, 'with': 10, 'is': 11, 'new': 12, 'না': 13, 'trump': 14, 'man': 15, 'from': 16, 'at': 17, 'ও': 18, 'about': 19, 'you': 20, 'this': 21, 'by': 22, 'নিয়ে': 23, 'after': 24, 'up': 25, 'out': 26, 'be': 27, 'how': 28, 'as': 29, 'it': 30, 'that': 31, 'not': 32, 'নিহত': 33, 'are': 34, 'থেকে': 35, 'your': 36, 'his': 37, 'দুই': 38, 'what': 39, 'নতুন': 40, 'he': 41, 'হবে': 42, 'all': 43, 'just': 44, 'who': 45, 'has': 46, 'will': 47, 'more': 48, 'one': 49, 'বাংলাদেশ': 50, 'into': 51, 'report': 52, 'year': 53, 'why': 54, 'have': 55, 'সঙ্গে': 56, 'area': 57, 'জন্য': 58, 'এক': 59, 'over': 60, 'donald': 61, 'u': 62, 'day': 63, 'says': 64, 's': 65, 'can': 66, 'first': 67, 'woman': 68, 'নেই': 69, 'পর': 70, 'time': 71, 'বাংলাদেশের': 72, 'like': 73, 'her': 74, "trump's": 75, 'old': 76, 'no': 77, 'get': 78, 'off': 79, 'করে': 80, 'গ্রেপ্তার': 81, 'an': 82, 'life': 83, 'people': 84, 'obama': 85, 'now': 86, 'শুরু': 87,

[ 5071 11859 11860 24360 24361     0     0     0     0     0     0     0
     0     0     0     0     0     0]
(31731, 18)


# Week-2 Word embedding

In [55]:
!pip install -q tensorflow-datasets 
# or "conda install -c anaconda tensorflow-datasets"

In [59]:
import tensorflow_datasets as tfds
import numpy as np

In [58]:
imdb, info = tfds.load("imdb_reviews",with_info=True, as_supervised=True)

Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Dataset imdb_reviews downloaded and prepared to /Users/msjahid/tensorflow_datasets/imdb_reviews/plain_text/0.1.0. Subsequent calls will reuse this data.


In [60]:
train_data, test_data = imdb['train'], imdb['test']

In [61]:
training_sentence =[]
training_labels = []

testing_sentence =[]
testing_labels = []

for s,l in train_data:
    training_sentence.append(str(s.numpy()))
    training_labels.append(l.numpy())
    
for s,l in test_data:
    testing_sentence.append(str(s.numpy()))
    testing_labels.append(l.numpy())
